import { ServicioGetDto } from "./ServicioGetDto";

export class ServicioGetModifiedDto extends ServicioGetDto{
    constructor(
        readonly updatedAt: Date,
        readonly updatedBy: number,
        id: number,
        folio: string,
        nombreSolicitante: string,
        nombreReceptor: string,
        fechaInicio: string,
        fechaTermino: string,
        horaInicio: string,
        horaTermino: string,
        descripcionFalla: string,
        descripcionActividad: string,
        nivel: string,
        fotos: number,
        observaciones: string,
        tipoEnvio: string,
        estatus: number,
        tipoServicio: string,
        codigoServicio: string,
        contratoId: number,
        tipoActividad: string,
        estadoServicio: string,
        direccion: string,
        dependencia: string,
        cargo: string,
        createdBy: number,
    ){
        super(
            id,
            folio,
            nombreSolicitante,
            nombreReceptor,
            fechaInicio,
            fechaTermino,
            horaInicio,
            horaTermino,
            descripcionFalla,
            descripcionActividad,
            nivel,
            fotos,
            observaciones,
            tipoEnvio,
            estatus,
            tipoServicio,
            codigoServicio,
            contratoId,
            tipoActividad,
            estadoServicio,
            direccion,
            dependencia,
            cargo,
            createdBy
        )
    }
}